<?php

namespace MZ\BlogBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * PostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsRepository extends DocumentRepository
{

    public function findAll()
    {
        $qb = $this->createQueryBuilder('Article')
               ->sort('createdAt', 'desc')
               ->getQuery()
               ->execute();
        return $qb;
    }

}